### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by deniederhut** [ORNL/tx2#2]
Love the docs! One nitpick -- there are a couple of objects you use, but don't show the import for (e.g. AutoTokenizer). Would you mind making those explicit?

**Comment by WildfireXIII** [comment]
Thanks! Basic usage code snippets were updated to show all imports as requested in commit 242a5551f65cd8d9ab5928293ba8388507837def

(linking for notification in main thread openjournals/joss-reviews#3652)
